//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HQLFormatException.java
//  @ Date : 2012/10/16
//  @ Author : 
//
//



package cn.richcloud.common.exception;


public class HQLFormatException extends RuntimeException{
}
